export const heroNames = {
  1: "Infernus",
  2: "Seven",
  3: "Vindicta",
  4: "Lady Geist",
  6: "Abrams",
  7: "Wraith",
  8: "McGinnis",
  10: "Paradox",
  11: "Dynamo",
  12: "Kelvin",
  13: "Haze",
  14: "Holliday",
  15: "Bebop",
  16: "Calico",
  17: "Grey Talon",
  18: "Mo & Krill",
  19: "Shiv",
  20: "Ivy",
  25: "Warden",
  27: "Yamato",
  31: "Lash",
  35: "Viscous",
  48: "Wrecker",
  50: "Pocket",
  52: "Mirage",
  53: "Fathom",
  58: "Vyper",
  60: "THE MAGNIFICENT SINCLAIR",
  61: "Trapper",
  62: "Raven"
};